### ISSUE TITLE
Any chance of an update

### ISSUE THREAD

**Issue by rbn920** [secureworkstation/rpm-amdgpu-pro-opencl#1]
Hi, love that you put this work in and have used the last couple of versions you have done. Any chance you will be updating this to the new drivers or should I fork it and see if I can figure it out myself?

Thanks again.

**Comment by secureworkstation** [comment]
I tried an update before, unfortunately this method stopped working (weird memory corruption). I started doing podman builds with this RPM. I'm sorry for this late reply.

**Comment by rbn920** [comment]
Hey no problem. Thanks for the update.
